import AccountPage from "../pages/AccountPage";
import CreateAccount from "../pages/CreateAccount";
import UserProfile from "../pages/UserProfile";
import ProfileName from "../pages/ProfileName";
import ProfileEmail from "../pages/ProfileEmail";
import ProfileMobileNumber from "../pages/ProfileMobileNumber";
import ProfileAddress from "../pages/ProfileAddress";
import ProfileChangePassword from "../pages/ProfileChangePassword";
import ProfileSetPassword from "../pages/ProfileSetPassword";
